; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
boards_dir = ./config

[env]
platform = espressif32@^6.12.0
board = board
framework = arduino, espidf
lib_deps = 
	thijse/ArduinoLog@^1.1.1
	lvgl/lvgl@^9.4.0
	adafruit/Adafruit ST7735 and ST7789 Library@^1.11.0
upload_speed = 921600
monitor_speed = 115200
board_build.partitions = ./config/partition.csv
board_build.filesystem = spiffs
build_flags = 
	-D LV_CONF_INCLUDE_SIMPLE
	-D LV_CONF_PATH=\"$PROJECT_DIR/include/lv_conf.h\"

[env:release]

[env:debug]
