#pragma once

// 多线程任务配置
#define TASK_SCREEN_CORE 1
#define TASK_SCREEN_PERIOD 10
#define TASK_SCREEN_STACK 8192
#define TASK_SCREEN_PRIORITY 1

#define TASK_BLE_CORE 1
#define TASK_BLE_PERIOD 1
#define TASK_BLE_STACK 4096
#define TASK_BLE_PRIORITY 1